services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sofia_db

  app:
    build: .
    environment:
      - MONGO_ATLAS_URL=${MONGO_ATLAS_URL:-mongodb://mongodb:27017/sofia_db}
      - JWT_SECRET=${JWT_SECRET:-default_jwt}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb-data: {}
