version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sofia_db

  sofia-api:
    image: openjdk:17-jdk-alpine
    environment:
      - MONGO_ATLAS_URL=${MONGO_ATLAS_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./target/com.sofia.backend-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - mongodb

volumes:
  mongodb-data:

