server:
  port: 8081

spring:
  application:
    name: com.sofia.backend

  data:
    mongodb:
      uri: mongodb://localhost/test

api:
  security:
    token:
      secret: ${JWT_SECRET:default-secret}
