server:
  port: 8080

spring:
  application:
    name: com.sofia.backend

  data:
    mongodb:
      uri: ${DATABASE_URL}

api:
  security:
    token:
      secret: ${JWT_SECRET}

consumer:
  api-flask:
    respostas:
      url: ${APIFLASK_RESPONSES_URL}

    resultado:
      url: ${APIFLASK_RESULT_URL}
