server:
  port: 8080

spring:
  application:
    name: com.sofia.backend

  data:
    mongodb:
      uri: ${MONGO_ATLAS_URL:mongodb://mongodb:27017/sofia_db}

api:
  security:
    token:
      secret: ${JWT_SECRET}

consumer:
  api-flask:
    respostas:
      url: http://127.0.0.1:8000/respostas

    resultado:
      url: http://127.0.0.1:8000/resultado
