server:
  port: 8081

spring:
  application:
    name: com.sofia.backend

  data:
    mongodb:
      uri: mongodb+srv://aasjunior:n1FZBGbgKDLDWpjn@sofia-cluster0.uminjta.mongodb.net/sofia_db?retryWrites=true&w=majority&appName=sofia-cluster0

api:
  security:
    token:
      secret: ${JWT_SECRET:default-secret}
