server:
  port: 8080

spring:
  application:
    name: com.sofia.backend

  data:
    mongodb:
      uri: mongodb+srv://aasjunior:n1FZBGbgKDLDWpjn@sofia-cluster0.uminjta.mongodb.net/sofia_db?retryWrites=true&w=majority&appName=sofia-cluster0

api:
  security:
    token:
      secret: ${JWT_SECRET:default-secret}

consumer:
  api-flask:
    respostas:
      url: http://127.0.0.1:5000/respostas

    resultado:
      url: http://127.0.0.1:5000/resultado
